  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Academic"
  weight = 200
  identifier = "Academic"
  url = "/Academic/"

  [[main]]
  name = "Work"
  weight = 300
  identifier = "Work"
  url = "/Work/"

  [[main]]
  name = "Awards"
  weight = 400
  identifier = "Awards"
  url = "/Awards/"

  [[main]]
  name = "Life"
  weight = 500
  identifier = "Life"

  [[main]]
  name = "Papers"
  weight = 510
  identifier = "papers"
  url = "/papers/"
  parent = "Academic"  

  [[main]]
  name = "Certifications"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
  parent = "Life"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"
