  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Academic"
  weight = 200
  identifier = "academic"
  url = "/academic/"

  [[main]]
  name = "Work"
  weight = 300
  identifier = "work"
  url = "/Work/"

  [[main]]
  name = "Awards"
  weight = 400
  identifier = "awards"
  url = "/awards/"

  [[main]]
  name = "Life"
  weight = 500
  identifier = "life"

  [[main]]
  name = "Papers"
  weight = 510
  identifier = "papers"
  url = "/papers/"
  parent = "academic"  

    [[main]]
  name = "Code"
  weight = 520
  identifier = "code"
  url = "/code/"
  parent = "academic"  

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"
